project:
  type: website
  output-dir: docs

website:
  title: "Quarto + GitHub Pages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [yeti, anari-custom.scss]
    toc: true
    



