project:
  type: website
  output-dir: docs

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [cosmo, anari-custom.scss]
    toc: true
    



